.TH "PHEX" "1" "August 22, 2019" "" "User Commands"

.SH NAME
phex \-make a hexdump or do the reverse

.SH SYNOPSIS
.B phex
[\fI\,FILE\/\fR]...

.SH DESCRIPTION
\fBphex\fR is referenced \fBxxd\fR.
.PP
\fBphex\fR creates a hex dump of a given file or standard input. It can also convert a hex dump back to its original binary form. Like \fBuuencode\fR(1) and \fBuudecode\fR(1) it allows the transmission of binary data in a 'mail-safe' ASCII representation, but has the advantage of decoding to standard output. 

.SH AUTHOR
Written by LeavaTail <starbow.duster@gmail.com>.

.SH "SEE ALSO"
\fBxxd\fR(1)
\fBuuencode\fR(1)
\fBuudecode\fR(1)

